"use client";

import { useState } from "react";
import TabBar from "@/components/ui/TabBar";
import DataTable from "@/components/ui/DataTable";
import Panel from "@/components/ui/Panel";
import AppButton from "@/components/ui/AppButton";
import StatusBadge from "@/components/ui/StatusBadge";
import MetricStatBlock from "@/components/ui/MetricStatBlock";

const TABS = ["All Reports", "Templates", "Scheduled"];

const COLUMNS = [
  { key: "name", label: "Report Name", mono: true },
  { key: "project", label: "Project" },
  { key: "type", label: "Type" },
  { key: "generatedBy", label: "Generated By" },
  { key: "date", label: "Date", mono: true },
  {
    key: "status",
    label: "Status",
    render: (val: unknown) => {
      const s = val as string;
      const v = s === "VALIDATED" ? "active" : s === "FAILED" ? "offline" : s === "PROCESSING" ? "alert" : "standby";
      return <StatusBadge variant={v}>{s}</StatusBadge>;
    },
  },
];

const DATA = [
  { name: "STKP_MON_JUL_2024", project: "Vortex Sector 7", type: "STOCKPILE", generatedBy: "J. Draven", date: "2024-07-12", status: "VALIDATED" },
  { name: "CUT_FILL_ANALYSIS_A2", project: "North Ridge Excavation", type: "VOLUMES", generatedBy: "A. Miller", date: "2024-07-10", status: "PROCESSING" },
  { name: "TOPO_SURVEY_Q2_FINAL", project: "Obsidian Depths", type: "TOPOGRAPHY", generatedBy: "S. Op", date: "2024-07-05", status: "VALIDATED" },
  { name: "DRILL_HOLE_TELEMETRY_EX", project: "Project Icarus", type: "DRILLING", generatedBy: "E. Lane", date: "2024-07-01", status: "FAILED" },
];

const TEMPLATES = [
  { name: "Monthly Stockpile", description: "Full volumetric analysis of all active stockpiles with error variance mapping.", active: true },
  { name: "Cut / Fill Balance", description: "Cross-sectional comparison between as-built and design surfaces." },
  { name: "Flight Telemetry", description: "Drone health metrics, GPS precision logs, and flight path visualization." },
];

export default function ReportsPage() {
  const [activeTab, setActiveTab] = useState(0);

  return (
    <div className="p-6 flex flex-col gap-6">
      <div className="flex items-center justify-between">
        <h1 className="text-accent text-lg font-bold uppercase tracking-wider">Reports</h1>
        <AppButton variant="primary" size="sm">New Generation</AppButton>
      </div>

      <div className="grid grid-cols-12 gap-6">
        <div className="col-span-8 flex flex-col gap-4">
          <TabBar tabs={TABS} activeIndex={activeTab} onChange={setActiveTab} />
          <Panel noPadding>
            <DataTable columns={COLUMNS} data={DATA} />
          </Panel>
        </div>
        <div className="col-span-4 flex flex-col gap-4">
          <Panel title="New Report Configuration">
            <div className="flex flex-col gap-1 mb-3">
              <span className="text-text-muted text-[10px] uppercase tracking-wider">Select Intelligence Template</span>
            </div>
            <div className="flex flex-col gap-2">
              {TEMPLATES.map((t) => (
                <div
                  key={t.name}
                  className={`p-3 rounded-sm border cursor-pointer transition-colors ${t.active ? "border-accent bg-accent/5" : "border-border-subtle hover:border-text-muted"
                    }`}
                >
                  <p className="text-text-primary text-xs font-semibold uppercase tracking-wider">{t.name}</p>
                  <p className="text-text-muted text-[10px] mt-1">{t.description}</p>
                </div>
              ))}
            </div>
            <div className="mt-4">
              <AppButton variant="primary" size="md" fullWidth>Generate Intelligence</AppButton>
            </div>
          </Panel>
          <div className="grid grid-cols-2 gap-4">
            <MetricStatBlock title="Storage" value="84.2%" subtitle="4.2 TB / 5.0 TB" />
            <MetricStatBlock title="Quota" value="12/15" subtitle="Reports Remaining" />
          </div>
        </div>
      </div>
    </div>
  );
}
